title: "UW Work"
description: "A collection of projects for UW front end"
baseurl: "/html300-2024" # Set to the repo name when deploying to GitHub Pages
url: "https://pamela-savagaonkar.github.io" # GitHub Pages URL
theme: jekyll-theme-minimal

exclude:
  - node_modules
  - vendor
  - dist
  - Gemfile
  - Gemfile.lock
